name: Deploy SAM Application

on:
  push:
    branches:
      - main  # Deploys on push to the main branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Match your Lambda's Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r hello_world/requirements.txt  # Install dependencies from the specified path

    - name: Install SAM CLI
      run: |
        pip install aws-sam-cli  # Install the AWS SAM CLI

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}  # Ensure this secret is set

    - name: Package SAM Application
      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}  # Pass the region as an environment variable
      run: |
        # Package the application using SAM CLI
        sam package \
          --template-file template.yaml \  # Specify your SAM template file
          --output-template-file packaged.yaml \
          --s3-bucket your-s3-bucket-name  # Replace with your S3 bucket name

    - name: Deploy SAM Application
      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}  # Ensure region is available for deployment
      run: |
        sam deploy \
          --template-file packaged.yaml \
          --stack-name your-stack-name \  # Replace with your CloudFormation stack name
          --capabilities CAPABILITY_IAM  # Required if your stack creates IAM roles