name: Deploy Lambda Function

on:
  push:
    branches:
      - main  # Deploys on push to the main branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Match your Lambda's Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assuming your Lambda's dependencies are listed in requirements.txt

    - name: Package Lambda Function
      run: |
        mkdir -p package
        # Copy code and dependencies to package directory
        cp -r . package/
        cd package
        zip -r ../lambda_function.zip .  # Package the Lambda function and dependencies
        cd ..

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name my-lambda-function-name \  # Replace with your Lambda function's name
          --zip-file fileb://lambda_function.zip