name: Deploy SAM Application

on:
  push:
    branches:
      - main  # Deploys on push to the main branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Match your Lambda's Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r hello_world/requirements.txt  # Install dependencies from the specified path

    - name: Install SAM CLI
      run: |
        pip install aws-sam-cli  # Install the AWS SAM CLI

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}  # Ensure this secret is set

    - name: Build SAM Application
      run: |
        sam build  # Build the SAM application

    - name: Deploy SAM Application
      run: |
        sam deploy --config-file samconfig.toml  # Deploy using the configurations in samconfig.toml
